<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GalleriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $indoorCategoryId = DB::table('gallery_categories')->where('slug_tr', 'ic-mekan')->first()->id;
        $outdoorCategoryId = DB::table('gallery_categories')->where('slug_tr', 'dis-mekan')->first()->id;
        $foodCategoryId = DB::table('gallery_categories')->where('slug_tr', 'yemek')->first()->id;

        // İç Mekan Fotoğrafları
        DB::table('galleries')->insert([
            [
                'category_id' => $indoorCategoryId,
                'image_path' => 'assets1/images/gallery/gallery-img-01.jpg',
                'title_tr' => 'İç Mekan Galeri Resmi 1',
                'title_en' => 'Indoor Gallery Image 1',
                'title_ar' => 'صورة معرض داخلي 1',
                'description_tr' => 'İç mekandaki atmosferimizden bazı görüntüler.',
                'description_en' => 'Some views from our indoor atmosphere.',
                'description_ar' => 'بعض الآراء من جو داخلي.',
                'is_active' => 1,
                'priority' => 1,
                'seo_title_tr' => 'İç Mekan Galerisi - Resim 1',
                'seo_title_en' => 'Indoor Gallery - Image 1',
                'seo_title_ar' => 'معرض داخلي - صورة 1',
                'seo_description_tr' => 'İç mekan galerimizden ilk resmin keyfini çıkarın.',
                'seo_description_en' => 'Enjoy the first image from our indoor gallery.',
                'seo_description_ar' => 'تمتع بالصورة الأولى من معرضنا الداخلي.',
                'seo_keywords_tr' => 'iç mekan, galeri, resim, atmosfer',
                'seo_keywords_en' => 'indoor, gallery, image, atmosphere',
                'seo_keywords_ar' => 'داخلي، معرض، صورة، جو',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $indoorCategoryId,
                'image_path' => 'assets1/images/gallery/gallery-img-02.jpg',
                'title_tr' => 'İç Mekan Galeri Resmi 1',
                'title_en' => 'Indoor Gallery Image 1',
                'title_ar' => 'صورة معرض داخلي 1',
                'description_tr' => 'İç mekandaki atmosferimizden bazı görüntüler.',
                'description_en' => 'Some views from our indoor atmosphere.',
                'description_ar' => 'بعض الآراء من جو داخلي.',
                'is_active' => 1,
                'priority' => 1,
                'seo_title_tr' => 'İç Mekan Galerisi - Resim 1',
                'seo_title_en' => 'Indoor Gallery - Image 1',
                'seo_title_ar' => 'معرض داخلي - صورة 1',
                'seo_description_tr' => 'İç mekan galerimizden ilk resmin keyfini çıkarın.',
                'seo_description_en' => 'Enjoy the first image from our indoor gallery.',
                'seo_description_ar' => 'تمتع بالصورة الأولى من معرضنا الداخلي.',
                'seo_keywords_tr' => 'iç mekan, galeri, resim, atmosfer',
                'seo_keywords_en' => 'indoor, gallery, image, atmosphere',
                'seo_keywords_ar' => 'داخلي، معرض، صورة، جو',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $indoorCategoryId,
                'image_path' => 'assets1/images/gallery/gallery-img-03.jpg',
                'title_tr' => 'İç Mekan Galeri Resmi 1',
                'title_en' => 'Indoor Gallery Image 1',
                'title_ar' => 'صورة معرض داخلي 1',
                'description_tr' => 'İç mekandaki atmosferimizden bazı görüntüler.',
                'description_en' => 'Some views from our indoor atmosphere.',
                'description_ar' => 'بعض الآراء من جو داخلي.',
                'is_active' => 1,
                'priority' => 1,
                'seo_title_tr' => 'İç Mekan Galerisi - Resim 1',
                'seo_title_en' => 'Indoor Gallery - Image 1',
                'seo_title_ar' => 'معرض داخلي - صورة 1',
                'seo_description_tr' => 'İç mekan galerimizden ilk resmin keyfini çıkarın.',
                'seo_description_en' => 'Enjoy the first image from our indoor gallery.',
                'seo_description_ar' => 'تمتع بالصورة الأولى من معرضنا الداخلي.',
                'seo_keywords_tr' => 'iç mekan, galeri, resim, atmosfer',
                'seo_keywords_en' => 'indoor, gallery, image, atmosphere',
                'seo_keywords_ar' => 'داخلي، معرض، صورة، جو',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Dış Mekan Fotoğrafları
        DB::table('galleries')->insert([

            [
                'category_id' => $outdoorCategoryId,
                'image_path' => 'assets1/images/gallery/gallery-img-04.jpg',
                'title_tr' => 'Dış Mekan Galeri Resmi 1',
                'title_en' => 'Outdoor Gallery Image 1',
                'title_ar' => 'صورة معرض خارجي 1',
                'description_tr' => 'Dış mekandaki atmosferimizden bazı görüntüler.',
                'description_en' => 'Some views from our outdoor atmosphere.',
                'description_ar' => 'بعض الآراء من جو خارجي.',
                'is_active' => 1,
                'priority' => 1,
                'seo_title_tr' => 'Dış Mekan Galerisi - Resim 1',
                'seo_title_en' => 'Outdoor Gallery - Image 1',
                'seo_title_ar' => 'معرض خارجي - صورة 1',
                'seo_description_tr' => 'Dış mekan galerimizden ilk resmin keyfini çıkarın.',
                'seo_description_en' => 'Enjoy the first image from our outdoor gallery.',
                'seo_description_ar' => 'تمتع بالصورة الأولى من معرضنا الخارجي.',
                'seo_keywords_tr' => 'dış mekan, galeri, resim, atmosfer',
                'seo_keywords_en' => 'outdoor, gallery, image, atmosphere',
                'seo_keywords_ar' => 'خارجي، معرض، صورة، جو',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $outdoorCategoryId,
                'image_path' => 'assets1/images/gallery/gallery-img-01.jpg',
                'title_tr' => 'Dış Mekan Galeri Resmi 1',
                'title_en' => 'Outdoor Gallery Image 1',
                'title_ar' => 'صورة معرض خارجي 1',
                'description_tr' => 'Dış mekandaki atmosferimizden bazı görüntüler.',
                'description_en' => 'Some views from our outdoor atmosphere.',
                'description_ar' => 'بعض الآراء من جو خارجي.',
                'is_active' => 1,
                'priority' => 1,
                'seo_title_tr' => 'Dış Mekan Galerisi - Resim 1',
                'seo_title_en' => 'Outdoor Gallery - Image 1',
                'seo_title_ar' => 'معرض خارجي - صورة 1',
                'seo_description_tr' => 'Dış mekan galerimizden ilk resmin keyfini çıkarın.',
                'seo_description_en' => 'Enjoy the first image from our outdoor gallery.',
                'seo_description_ar' => 'تمتع بالصورة الأولى من معرضنا الخارجي.',
                'seo_keywords_tr' => 'dış mekan, galeri, resim, atmosfer',
                'seo_keywords_en' => 'outdoor, gallery, image, atmosphere',
                'seo_keywords_ar' => 'خارجي، معرض، صورة، جو',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $outdoorCategoryId,
                'image_path' => 'assets1/images/gallery/gallery-img-01.jpg',
                'title_tr' => 'Dış Mekan Galeri Resmi 1',
                'title_en' => 'Outdoor Gallery Image 1',
                'title_ar' => 'صورة معرض خارجي 1',
                'description_tr' => 'Dış mekandaki atmosferimizden bazı görüntüler.',
                'description_en' => 'Some views from our outdoor atmosphere.',
                'description_ar' => 'بعض الآراء من جو خارجي.',
                'is_active' => 1,
                'priority' => 1,
                'seo_title_tr' => 'Dış Mekan Galerisi - Resim 1',
                'seo_title_en' => 'Outdoor Gallery - Image 1',
                'seo_title_ar' => 'معرض خارجي - صورة 1',
                'seo_description_tr' => 'Dış mekan galerimizden ilk resmin keyfini çıkarın.',
                'seo_description_en' => 'Enjoy the first image from our outdoor gallery.',
                'seo_description_ar' => 'تمتع بالصورة الأولى من معرضنا الخارجي.',
                'seo_keywords_tr' => 'dış mekan, galeri, resim, atmosfer',
                'seo_keywords_en' => 'outdoor, gallery, image, atmosphere',
                'seo_keywords_ar' => 'خارجي، معرض، صورة، جو',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => $foodCategoryId,
                'image_path' => 'assets1/images/gallery/gallery-img-02.jpg',
                'title_tr' => 'Yemek Galeri Resmi 1',
                'title_en' => 'Food Gallery Image 1',
                'title_ar' => 'صورة معرض الطعام 1',
                'description_tr' => 'Menümüzden bazı leziz yemekler.',
                'description_en' => 'Some delicious dishes from our menu.',
                'description_ar' => 'بعض الأطعمة اللذيذة من قائمتنا.',
                'is_active' => 1,
                'priority' => 2,
                'seo_title_tr' => 'Yemek Galerisi - Resim 1',
                'seo_title_en' => 'Food Gallery - Image 1',
                'seo_title_ar' => 'معرض الطعام - صورة 1',
                'seo_description_tr' => 'Yemek galerimizden ilk resmin keyfini çıkarın.',
                'seo_description_en' => 'Enjoy the first image from our food gallery.',
                'seo_description_ar' => 'تمتع بالصورة الأولى من معرض الطعام لدينا.',
                'seo_keywords_tr' => 'yemek, galeri, resim, menü',
                'seo_keywords_en' => 'food, gallery, image, menu',
                'seo_keywords_ar' => 'طعام، معرض، صورة، قائمة',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'category_id' => $foodCategoryId,
                'image_path' => 'assets1/images/gallery/gallery-img-03.jpg',
                'title_tr' => 'Yemek Galeri Resmi 2',
                'title_en' => 'Food Gallery Image 2',
                'title_ar' => 'صورة معرض الطعام 2',
                'description_tr' => 'Menümüzden bazı leziz yemekler.',
                'description_en' => 'Some delicious dishes from our menu.',
                'description_ar' => 'بعض الأطعمة اللذيذة من قائمتنا.',
                'is_active' => 1,
                'priority' => 2,
                'seo_title_tr' => 'Yemek Galerisi - Resim 1',
                'seo_title_en' => 'Food Gallery - Image 1',
                'seo_title_ar' => 'معرض الطعام - صورة 1',
                'seo_description_tr' => 'Yemek galerimizden ilk resmin keyfini çıkarın.',
                'seo_description_en' => 'Enjoy the first image from our food gallery.',
                'seo_description_ar' => 'تمتع بالصورة الأولى من معرض الطعام لدينا.',
                'seo_keywords_tr' => 'yemek, galeri, resim, menü',
                'seo_keywords_en' => 'food, gallery, image, menu',
                'seo_keywords_ar' => 'طعام، معرض، صورة، قائمة',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'category_id' => $foodCategoryId,
                'image_path' => 'assets1/images/gallery/gallery-img-04.jpg',
                'title_tr' => 'Yemek Galeri Resmi 3',
                'title_en' => 'Food Gallery Image 3',
                'title_ar' => 'صورة معرض الطعام 3',
                'description_tr' => 'Menümüzden bazı leziz yemekler.',
                'description_en' => 'Some delicious dishes from our menu.',
                'description_ar' => 'بعض الأطعمة اللذيذة من قائمتنا.',
                'is_active' => 1,
                'priority' => 2,
                'seo_title_tr' => 'Yemek Galerisi - Resim 1',
                'seo_title_en' => 'Food Gallery - Image 1',
                'seo_title_ar' => 'معرض الطعام - صورة 1',
                'seo_description_tr' => 'Yemek galerimizden ilk resmin keyfini çıkarın.',
                'seo_description_en' => 'Enjoy the first image from our food gallery.',
                'seo_description_ar' => 'تمتع بالصورة الأولى من معرض الطعام لدينا.',
                'seo_keywords_tr' => 'yemek, galeri, resim, menü',
                'seo_keywords_en' => 'food, gallery, image, menu',
                'seo_keywords_ar' => 'طعام، معرض، صورة، قائمة',
                'created_at' => now(),
                'updated_at' => now(),
            ]


        ]);
    }
}
