<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SliderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Fapel Restaurant için 2 adet slider ekle
        DB::table('sliders')->insert([
            [
                'page_name'=>'home',
                'first_title_tr' => 'Fapel Restaurant\'a Hoş Geldiniz',
                'first_title_en' => 'Welcome to Fapel Restaurant',
                'first_title_ar' => 'مرحبًا بكم في مطعم فابل',
                'second_title_tr' => 'Lezzetli Yemeklerimizle Sizi Ağırlamaktan Mutluluk Duyarız',
                'second_title_en' => 'We are Delighted to Host You with Our Delicious Meals',
                'second_title_ar' => 'نحن مسرورون لاستضافتكم مع وجباتنا اللذيذة',
                'is_active' => 1,
                'priority' => 1,
                'img'=>'assets1/images/bg/bg-image-2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'page_name'=>'home',
                'first_title_tr' => 'Özel Etkinlikler İçin Mekanımızı Kiralayabilirsiniz',
                'first_title_en' => 'You Can Rent Our Venue for Special Events',
                'first_title_ar' => 'يمكنك استئجار مكاننا للفعاليات الخاصة',
                'second_title_tr' => 'Unutulmaz Anlarınıza Tanıklık Etmek İçin Bekliyoruz',
                'second_title_en' => 'We Are Waiting to Witness Your Unforgettable Moments',
                'second_title_ar' => 'نحن ننتظر أن نشهد لحظاتك التي لا تُنسى',
                'is_active' => 1,
                'priority' => 2,
                'img'=>'assets1/images/bg/bg-image-3.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'page_name'=>'home',
                'first_title_tr' => 'Fapel Restaurant\'ın Eşsiz Ambiyansında Romantik Akşamlar',
                'first_title_en' => 'Romantic Evenings in the Unique Ambiance of Fapel Restaurant',
                'first_title_ar' => 'أمسيات رومانسية في أجواء مطعم فابل الفريدة',
                'second_title_tr' => 'Sevdiklerinizle Kaliteli Zaman Geçirin',
                'second_title_en' => 'Spend Quality Time with Your Loved Ones',
                'second_title_ar' => 'قضاء وقت ذات جودة مع أحبائك',
                'is_active' => 1,
                'priority' => 3,
                'img'=>'assets1/images/bg/menu-section.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'page_name'=>'home',
                'first_title_tr' => 'Fapel Restaurant\'ın Özenle Hazırlanmış Menüsü',
                'first_title_en' => 'Carefully Prepared Menu of Fapel Restaurant',
                'first_title_ar' => 'قائمة مطعم فابل المعدة بعناية',
                'second_title_tr' => 'Ağızda Dağılan Lezzetlerle Tanışın',
                'second_title_en' => 'Meet the Flavors that Melt in Your Mouth',
                'second_title_ar' => 'تعرف على النكهات التي تذوب في فمك',
                'is_active' => 1,
                'priority' => 4,
                'img'=>'assets1/images/bg/video-bg.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'page_name'=>'home',
                'first_title_tr' => 'Fapel Restaurant\'ın Özenle Hazırlanmış Menüsü',
                'first_title_en' => 'Carefully Prepared Menu of Fapel Restaurant',
                'first_title_ar' => 'قائمة مطعم فابل المعدة بعناية',
                'second_title_tr' => 'Ağızda Dağılan Lezzetlerle Tanışın',
                'second_title_en' => 'Meet the Flavors that Melt in Your Mouth',
                'second_title_ar' => 'تعرف على النكهات التي تذوب في فمك',
                'is_active' => 1,
                'priority' => 4,
                'img'=>'assets1/images/bg/video-bg.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'page_name'=>'about',
                // Burada gerçek verilerinizle doldurmanız gereken örnek başlıklar var
                'first_title_tr' => 'Hakkımızda',
                'first_title_en' => 'About Us',
                'first_title_ar' => 'معلومات عنا',
                'second_title_tr' => 'Biz Kimiz?',
                'second_title_en' => 'Who Are We?',
                'second_title_ar' => 'من نحن؟',
                'is_active' => 1,
                'priority' => 2,
                'img'=>'assets1/images/breadcrumbs/about.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ... benzeri şekilde diğer sayfalar için de ekleyebilirsiniz
            [
                'page_name'=>'contact',
                'first_title_tr' => 'Bize Ulaşın',
                'first_title_en' => 'Contact Us',
                'first_title_ar' => 'اتصل بنا',
                'second_title_tr' => 'İletişim',
                'second_title_en' => 'Contact Details',
                'second_title_ar' => 'تفاصيل الاتصال',
                'is_active' => 1,
                'priority' => 3,
                'img'=>'assets1/images/breadcrumbs/chef.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'page_name'=>'reservation',
                'first_title_tr' => 'Rezervasyon',
                'first_title_en' => 'Make a Reservation',
                'first_title_ar' => 'احجز الآن',
                'second_title_tr' => 'Mekanımızda Yer Ayırtın',
                'second_title_en' => 'Reserve Your Spot at Our Venue',
                'second_title_ar' => 'احجز مكانك في مكاننا',
                'is_active' => 1,
                'priority' => 4,
                'img'=>'assets1/images/breadcrumbs/chef.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'page_name'=>'menu',
                'first_title_tr' => 'Menü',
                'first_title_en' => 'Our Menu',
                'first_title_ar' => 'قائمتنا',
                'second_title_tr' => 'Lezzetli Yemeklerimizi Keşfedin',
                'second_title_en' => 'Discover Our Delicious Dishes',
                'second_title_ar' => 'اكتشف أطباقنا اللذيذة',
                'is_active' => 1,
                'priority' => 5,
                'img'=>'assets1/images/breadcrumbs/chef.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'page_name'=>'blog',
                'first_title_tr' => 'Blog',
                'first_title_en' => 'Blog',
                'first_title_ar' => 'مدونة',
                'second_title_tr' => 'Son Yazılarımıza Göz Atın',
                'second_title_en' => 'Check Our Latest Posts',
                'second_title_ar' => 'راجع آخر مشاركاتنا',
                'is_active' => 1,
                'priority' => 6,
                'img'=>'assets1/images/breadcrumbs/about.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'page_name'=>'blog',
                'first_title_tr' => 'Blog',
                'first_title_en' => 'Blog',
                'first_title_ar' => 'مدونة',
                'second_title_tr' => 'Son Yazılarımıza Göz Atın',
                'second_title_en' => 'Check Our Latest Posts',
                'second_title_ar' => 'راجع آخر مشاركاتنا',
                'is_active' => 1,
                'priority' => 6,
                'img'=>'assets1/images/breadcrumbs/about.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'page_name' => 'gallery',
                'first_title_tr' => 'Foto-Galeri',
                'first_title_en' => 'Gallery',
                'first_title_ar' => 'معرض',
                'second_title_tr' => 'Lezzetlerimizin Görsel Ziyafetine Göz Atın',
                'second_title_en' => 'Take a Look at the Visual Feast of Our Flavors',
                'second_title_ar' => 'ألق نظرة على عرضنا البصري للأطعمة',
                'is_active' => 1,
                'priority' => 7,
                'img' => 'assets1/images/breadcrumbs/chef.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
